openapi: 3.0.0
info:
  title: Task API
  version: 1.0.0
paths:
  /tasks:
    post:
      summary: Create a task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        201:
          description: Task created
    get:
      summary: Get all tasks
      responses:
        200:
          description: List of tasks
  /tasks/{id}:
    put:
      summary: Update a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        200:
          description: Task updated
    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Task deleted
components:
  schemas:
    Task:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
